---
- hosts: localhost
  tasks:
  - name: Generate self-signed certificate
    shell: |
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=example.com/O=example.com"
    ignore_errors: yes

  - name: Create Kubernetes secret for TLS
    shell: |
      kubectl create secret tls tls-secret --key tls.key --cert tls.crt
    ignore_errors: yes
    retries: 3
    delay: 10
  - name: Deploy Nginx Ingress Controller
    shell: |
      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      helm repo update
      helm install my-nginx-ingress ingress-nginx/ingress-nginx
    ignore_errors: yes
    retries: 3
    delay: 10
  - name: Deploy Hello World Application
    shell: |
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
      kubectl apply -f ingress.yaml
    ignore_errors: yes
    retries: 5
    delay: 10